name: functionally
description: A library designed to help develop code in a more FP oriented way.
version: 0.0.1-dev.7
repository: https://github.com/fgaudo/functionally

environment:
  sdk: ^3.2.3

dependencies:
  rxdart: ^0.27.7

dev_dependencies:
  coverage: ^1.7.1
  lints: ^3.0.0
  test: ^1.21.0
