name: functionally
description: A library for functional goodies.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

dependencies:
  rxdart: ^0.27.7

dev_dependencies:
  coverage: ^1.7.1
  lints: ^3.0.0
  test: ^1.21.0
