name: functionally
description: A library for functional goodies.
version: 0.0.1-dev.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.2

dependencies:
  rxdart: ^0.27.7

dev_dependencies:
  coverage: ^1.7.1
  lints: ^3.0.0
  test: ^1.21.0
